name: Build PHP
on:
  workflow_dispatch:
    inputs:
      selectos:
        required: true
        description: Build target OS
        default: 'linux-x86_64'
        type: choice
        options:
          - 'linux-x86_64'
          - 'linux-aarch64'
          - 'linux-x86_64-glibc'
          - 'linux-aarch64-glibc'
          - 'macos-x86_64'
          - 'macos-aarch64'
      php-version:
        required: true
        description: PHP version to compile
        default: '8.4'
        type: choice
        options:
          - '8.4'
          - '8.3'
          - '8.2'
          - '8.1'
      create-docker:
        description: 'Create a docker image'
        type: boolean
        default: true

jobs:
  unix-static-build:
    uses: yoramdelangen/static-php-cli/.github/workflows/build-unix.yml@feat/workflow-call-with-vendor-mode
    with:
      os: ${{ inputs.selectos }}
      php-version: ${{ inputs.php-version }}
      extensions: 'odbc,pdo_odbc,bcmath,calendar,ctype,curl,dba,exif,fileinfo,filter,gd,intl,libxml,mbregex,mbstring,msgpack,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pdo_sqlsrv,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite4,sqlsrv,tokenizer,xml,xmlreader,xmlwriter,zip,zlib'
      vendor-mode: true
